In [1]:
import numpy as np 
import pandas as pd

In [2]:
movie = pd.read_csv("movies_metadata.csv" , low_memory= False)
movie.head(5)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [3]:
movie.info()
movie.isnull().mean()*100

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  float64
 16  runtime                45203 non-null  float64
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  float64
 23  vote_count             45460 non-null  float64
dtypes: float64(4), object(20)
memory usage: 8.3+ MB

adult                     0.000000
belongs_to_collection    90.115691
budget                    0.000000
genres                    0.000000
homepage                 82.883913
id                        0.000000
imdb_id                   0.037391
original_language         0.024194
original_title            0.000000
overview                  2.098271
popularity                0.010997
poster_path               0.848986
production_companies      0.006598
production_countries      0.006598
release_date              0.191352
revenue                   0.013197
runtime                   0.578454
spoken_languages          0.013197
status                    0.191352
tagline                  55.104914
title                     0.013197
video                     0.013197
vote_average              0.013197
vote_count                0.013197
dtype: float64

In [4]:
C = movie["vote_average"].mean()

In [5]:
C

np.float64(5.618207215134184)

In [6]:
m = movie["vote_count"].quantile(0.90)
m

np.float64(160.0)

In [7]:
new_movie = movie.copy().loc[movie["vote_count"] >= m]

In [8]:
new_movie.shape

(4555, 24)

In [9]:
def rating(x, C=C, m=m):
    v = x["vote_count"]
    r = x["vote_average"]
    return (v/(v+m) * r) + (m/(v+m) * C)

In [10]:
movie.apply(rating , axis=1)

0        7.640253
1        6.820293
2        5.940132
3        5.702645
4        5.660700
           ...
45461    5.608156
45462    5.680449
45463    5.552489
45464    5.618207
45465    5.618207
Length: 45466, dtype: float64

In [11]:
new_movie.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [12]:
new_movie["score"] = new_movie.apply(rating ,axis=1)

In [13]:
new_movie = new_movie.sort_values("score" , ascending = False)

In [14]:
new_movie.loc[: , ["title" , "release_date" , "revenue" , "score"]].head(20)

                                 title release_date       revenue     score
314           The Shawshank Redemption   1994-09-23  2.834147e+07  8.445869
834                      The Godfather   1972-03-14  2.450664e+08  8.425439
10309      Dilwale Dulhania Le Jayenge   1995-10-20  1.000000e+08  8.421453
12481                  The Dark Knight   2008-07-16  1.004558e+09  8.265477
2843                        Fight Club   1999-10-15  1.008538e+08  8.256385
292                       Pulp Fiction   1994-09-10  2.139288e+08  8.251406
522                   Schindler's List   1993-11-29  3.213656e+08  8.206639
23673                         Whiplash   2014-10-10  1.309200e+07  8.205404
5481                     Spirited Away   2001-07-20  2.749251e+08  8.196055
2211                 Life Is Beautiful   1997-12-20  2.294000e+08  8.187171
1178            The Godfather: Part II   1974-12-20  4.754284e+07  8.180076
1152   One Flew Over the Cuckoo's Nest   1975-11-18  1.089813e+08  8.164256
351                       Forrest Gump   1994-07-06  6.779454e+08  8.150272
1154           The Empire Strikes Back   1980-05-17  5.384000e+08  8.132919
1176                            Psycho   1960-06-16  3.200000e+07  8.132715
18465                 The Intouchables   2011-11-02  4.264809e+08  8.125837
40251                       Your Name.   2016-08-26  3.552983e+08  8.112532
289             Leon: The Professional   1994-09-14  4.528497e+07  8.107234
3030                    The Green Mile   1999-12-10  2.846000e+08  8.104511
1170                        GoodFellas   1990-09-12  4.683639e+07  8.077459

In [15]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction import text

# custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'boom'}))

# tfidf = TfidfVectorizer(stop_words=custom_stopwords)

# movie["overview"] = movie["overview"].fillna("")

# tfidf_matrix = tfidf.fit_transform(movie["overview"])
# tfidf_matrix.shape

In [16]:
custom_stopwords = list(text.ENGLISH_STOP_WORDS.union({'boom'})) # This has all the enlish words like and , or ,  they because these words make the process slow and have no big value 
 # see this is custom word if you want you can use this method too remove a custom word too

tfidf = TfidfVectorizer(stop_words=custom_stopwords)

movie["overview"] = movie["overview"].fillna(" ")

tfidf_matrix = tfidf.fit_transform(movie["overview"])
tfidf_matrix.shape

(45466, 75826)

In [17]:
# Here we used list because English_stop_words is a frozen set and to use that we have to pass this is list

In [18]:
tfidf.get_feature_names_out()[5000:5010]

array(['avails', 'avaks', 'avalanche', 'avalanches', 'avallone', 'avalon',
       'avant', 'avanthika', 'avanti', 'avaracious'], dtype=object)

In [19]:
# from sklearn.metrics.pairwise import linear_kernel
# indices = pd.Series(movie.index, index=movie['title']).drop_duplicates()
# idx = indices["The Dark Knight Rises"]
# cosine_sim = linear_kernel(tfidf_matrix[idx:idx+1], tfidf_matrix)

In [20]:
from sklearn.metrics.pairwise import linear_kernel
import pandas as pd

indices = pd.Series(movie.index, index=movie['title']).drop_duplicates()

def get_recommendations(title):
    idx = indices[title]

    cosine_sim = linear_kernel(tfidf_matrix[idx:idx+1], tfidf_matrix)

    sim_scores = list(enumerate(cosine_sim[0]))

    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

    sim_scores = sim_scores[1:11]

    movie_indices = [i[0] for i in sim_scores]

    return movie.iloc[movie_indices][['title', 'release_date', 'vote_average']]

In [21]:
get_recommendations("The Dark Knight Rises")

,title,release_date,vote_average
12481,The Dark Knight,2008-07-16,8.3
150,Batman Forever,1995-06-16,5.2
1328,Batman Returns,1992-06-19,6.6
15511,Batman: Under the Red Hood,2010-07-27,7.6
585,Batman,1989-06-23,7.0
21194,Batman Unmasked: The Psychology of the Dark Kn...,2008-07-15,8.0
9230,Batman Beyond: Return of the Joker,2000-12-12,7.5
18035,Batman: Year One,2011-09-27,7.1
19792,"Batman: The Dark Knight Returns, Part 1",2012-09-06,7.7
3095,Batman: Mask of the Phantasm,1993-12-25,7.4

In [22]:
credits = pd.read_csv("credits.csv")
keywords = pd.read_csv("keywords.csv")

In [23]:
movie= movie.drop([19730, 29503, 35587])

In [24]:
movie["id"] = movie["id"].astype("int64")

In [25]:
movie = movie.merge(credits , on="id")
movie = movie.merge(keywords , on="id")

In [26]:
movie.head(1)

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,spoken_languages,status,tagline,title,video,vote_average,vote_count,cast,crew,keywords
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...","[{'id': 931, 'name': 'jealousy'}, {'id': 4290,..."

In [27]:
# literal_eval = turn string into list so that we can extract the given data easily

from ast import literal_eval
features = ['cast', 'crew', 'keywords', 'genres']
for feature in features:
    movie[feature] = movie[feature].apply(literal_eval)

In [28]:
import numpy as np
def director(x):
    for i in x:
        if i["job"]=="Director":
            return i["name"]
    return np.nan

In [29]:
def get_list(x):
    if isinstance(x,list):
        return[i["name"] for i in x[:3]]
    else:
        return[]

In [33]:
movie["director"] = movie["crew"].apply(director)
features = ['cast', 'keywords', 'genres']
for feature in features:
    movie[feature] = movie[feature].apply(get_list)

In [35]:

movie[['title', 'cast', 'director', 'keywords', 'genres']].head(3)

,title,cast,director,keywords,genres
0,Toy Story,"[Tom Hanks, Tim Allen, Don Rickles]",John Lasseter,"[jealousy, toy, boy]","[Animation, Comedy, Family]"
1,Jumanji,"[Robin Williams, Jonathan Hyde, Kirsten Dunst]",Joe Johnston,"[board game, disappearance, based on children'...","[Adventure, Fantasy, Family]"
2,Grumpier Old Men,"[Walter Matthau, Jack Lemmon, Ann-Margret]",Howard Deutch,"[fishing, best friend, duringcreditsstinger]","[Romance, Comedy]"

In [36]:
def clean_data(x):
    if isinstance(x, list):
        return [str.lower(i.replace(" ", "")) for i in x]
    else:
        #Check if director exists. If not, return empty string
        if isinstance(x, str):
            return str.lower(x.replace(" ", ""))
        else:
            return ''

In [38]:
features = ['cast', 'keywords', 'director', 'genres']

for feature in features:
    movie[feature] = movie[feature].apply(clean_data)

In [39]:
def create_soup(x):
    return ' '.join(x['keywords']) + ' ' + ' '.join(x['cast']) + ' ' + x['director'] + ' ' + ' '.join(x['genres'])

In [40]:

movie['soup'] = movie.apply(create_soup, axis=1)

In [42]:
from sklearn.feature_extraction.text import CountVectorizer

count = CountVectorizer(stop_words='english')
count_matrix = count.fit_transform(movie['soup'])

In [59]:
from sklearn.metrics.pairwise import cosine_similarity

def get_recommendations(title):
    idx = indices[title]

    
    sim_scores = cosine_similarity(count_matrix[idx], count_matrix).flatten()

    sim_scores = list(enumerate(sim_scores))

   
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)

   
    sim_scores = sim_scores[1:11]

    movie_indices = [i[0] for i in sim_scores]

    return movie['title'].iloc[movie_indices]

In [60]:
movie = movie.reset_index(drop=True)
indices = pd.Series(movie.index, index=movie['title'])

In [62]:
get_recommendations("Arrival")

22481                            Apnea
33276                         Infinite
39808                     Dustbin Baby
46319                      Getting Out
37951                         Atlantis
1217     The Day the Earth Stood Still
13232    The Day the Earth Stood Still
21725                          Gravity
2948                       Light It Up
17369                      Interkosmos
Name: title, dtype: object